const fullCountryCodes = [
    { code: "+1", name: "United States / Canada" }, { code: "+7", name: "Russia / Kazakhstan" },
    { code: "+20", name: "Egypt" }, { code: "+27", name: "South Africa" }, { code: "+30", name: "Greece" },
    { code: "+31", name: "Netherlands" }, { code: "+32", name: "Belgium" }, { code: "+33", name: "France" },
    { code: "+34", name: "Spain" }, { code: "+36", name: "Hungary" }, { code: "+39", name: "Italy" },
    { code: "+40", name: "Romania" }, { code: "+41", name: "Switzerland" }, { code: "+44", name: "United Kingdom" },
    { code: "+46", name: "Sweden" }, { code: "+47", name: "Norway" }, { code: "+48", name: "Poland" },
    { code: "+49", name: "Germany" }, { code: "+51", name: "Peru" }, { code: "+52", name: "Mexico" },
    { code: "+54", name: "Argentina" }, { code: "+55", name: "Brazil" }, { code: "+56", name: "Chile" },
    { code: "+57", name: "Colombia" }, { code: "+58", name: "Venezuela" }, { code: "+60", name: "Malaysia" },
    { code: "+61", name: "Australia" }, { code: "+62", name: "Indonesia" }, { code: "+63", name: "Philippines" },
    { code: "+64", name: "New Zealand" }, { code: "+65", name: "Singapore" }, { code: "+66", name: "Thailand" },
    { code: "+81", name: "Japan" }, { code: "+82", name: "South Korea" }, { code: "+84", name: "Vietnam" },
    { code: "+86", name: "China" }, { code: "+90", name: "Turkey" }, { code: "+91", name: "India" },
    { code: "+92", name: "Pakistan" }, { code: "+93", name: "Afghanistan" }, { code: "+94", name: "Sri Lanka" },
    { code: "+95", name: "Myanmar" }, { code: "+98", name: "Iran" }, { code: "+212", name: "Morocco" },
    { code: "+213", name: "Algeria" }, { code: "+234", name: "Nigeria" }, { code: "+254", name: "Kenya" },
    { code: "+351", name: "Portugal" }, { code: "+353", name: "Ireland" }, { code: "+358", name: "Finland" },
    { code: "+380", name: "Ukraine" }, { code: "+966", name: "Saudi Arabia" }, { code: "+971", name: "United Arab Emirates" },
    { code: "+972", name: "Israel" }
];

const allCurrencies = [
    "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN",
    "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL",
    "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLP", "CNY",
    "COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD",
    "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS",
    "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF",
    "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD",
    "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT",
    "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD",
    "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN",
    "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK",
    "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR",
    "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLL", "SOS", "SRD", "SSP",
    "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY",
    "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VES", "VND",
    "VUV", "WST", "XAF", "XCD", "XDR", "XOF", "XPF", "YER", "ZAR", "ZMW", "ZWL"
];
